"""add file metadata columns to documents

Revision ID: 368258255e0b
Revises: ee6251779395
Create Date: 2026-09-04 10:21:59.304853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368258255e0b'
down_revision: Union[str, Sequence[str], None] = 'ee6251779395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(length=512), nullable=False))
    op.add_column('documents', sa.Column('file_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'documents', ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'file_name')
    # ### end Alembic commands ###
