"""create users and documents with mapped relationships

Revision ID: 5746c6f344f3
Revises: e050af0fbe21
Create Date: 2026-08-29 15:58:57.441725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5746c6f344f3'
down_revision: Union[str, Sequence[str], None] = 'e050af0fbe21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
